# Generated by Django 2.1.4 on 2018-12-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='preperation_time',
        ),
    ]
