# Generated by Django 2.1.4 on 2018-12-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_remove_meals_preperation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='preperation_time',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
