# Generated by Django 2.1.4 on 2018-12-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_meals_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
