# Generated by Django 2.1.4 on 2019-01-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'about us ', 'verbose_name_plural': 'about us '},
        ),
        migrations.AlterModelOptions(
            name='chef',
            options={'verbose_name': 'chef', 'verbose_name_plural': 'chef'},
        ),
        migrations.AlterModelOptions(
            name='why_choose_us',
            options={'verbose_name': 'why choose us ', 'verbose_name_plural': 'why choose us '},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
    ]
